#### lol, now we are doing tensors?
how do we manipulate tensors in pytorch

In [1]:
import torch

In [ ]:
distances = torch.tensor([[3.0, 7.0], [12.0, 18.0], [22.0, 28.0]], device='mps', dtype=torch.float32)
print(distances.shape)

torch.Size([3, 2])


In [10]:
from torch import nn

In [12]:
simple_model = nn.Linear(2, 1, device='mps')
output = simple_model(distances)

In [14]:
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

mixed_tensor = float_tensor + int_tensor
print(mixed_tensor.dtype)


torch.float32


In [15]:
single_distance = torch.tensor(25.0)
single_distance.shape

torch.Size([])

In [19]:
single_distance.unsqueeze(0).unsqueeze(0).shape

torch.Size([1, 1])

In [17]:
single_distance.unsqueeze(0)

tensor([25.])

In [20]:
### performing broadcast operations with torch tensor math
distances = torch.tensor([[3.0], [7.0], [12.0]])
weight =  2.3
bias = 1.0


outputs = weight * distances + bias
print(outputs)

tensor([[ 7.9000],
        [17.1000],
        [28.6000]])


In [28]:
complex_tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]])
op_tensor = torch.tensor([2, 1, 0, 1]).unsqueeze(1)

complex_tensor.shape

torch.Size([4, 2])

In [29]:
op_tensor.shape

torch.Size([4, 1])

In [30]:
outputs = complex_tensor * op_tensor
print(outputs)



tensor([[2., 4.],
        [3., 4.],
        [0., 0.],
        [7., 8.]])


In [31]:
import numpy as np

In [32]:
# From a NumPy array
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
torch_tensor_from_numpy = torch.from_numpy(numpy_array)

print("TENSOR FROM NUMPY:\n\n", torch_tensor_from_numpy)

TENSOR FROM NUMPY:

 tensor([[1, 2, 3],
        [4, 5, 6]])


In [33]:
zeros = torch.zeros(2, 3)

print("TENSOR WITH ZEROS:\n\n", zeros)


TENSOR WITH ZEROS:

 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [34]:
ones = torch.ones(2, 3)

print("TENSOR WITH ONES:\n\n", ones)

TENSOR WITH ONES:

 tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [35]:
# Random numbers
random = torch.rand(2, 3)

print("RANDOM TENSOR:\n\n", random)

RANDOM TENSOR:

 tensor([[0.9131, 0.2723, 0.6759],
        [0.3623, 0.4446, 0.0521]])


In [36]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Boolean indexing using logical comparisons
mask = x > 6

print("MASK (VALUES > 6):\n\n", mask, "\n")

# Applying Boolean masking
mask_applied = x[mask]

print("VALUES AFTER APPLYING MASK:", mask_applied, "\n")

NameError: name 'x' is not defined

In [37]:
temperatures = torch.tensor([20, 35, 19, 35, 42])
print("TEMPERATURES:", temperatures)
print("-" * 50)

### Comparison Operators (>, <, ==)

# Use '>' (greater than) to find temperatures above 30
is_hot = temperatures > 30

# Use '<=' (less than or equal to) to find temperatures 20 or below
is_cool = temperatures <= 20

# Use '==' (equal to) to find temperatures exactly equal to 35
is_35_degrees = temperatures == 35

print("\nHOT (> 30 DEGREES):", is_hot)
print("COOL (<= 20 DEGREES):", is_cool)
print("EXACTLY 35 DEGREES:", is_35_degrees, "\n")

TEMPERATURES: tensor([20, 35, 19, 35, 42])
--------------------------------------------------

HOT (> 30 DEGREES): tensor([False,  True, False,  True,  True])
COOL (<= 20 DEGREES): tensor([ True, False,  True, False, False])
EXACTLY 35 DEGREES: tensor([False,  True, False,  True, False]) 



In [38]:
is_morning = torch.tensor([True, False, False, True])
is_raining = torch.tensor([False, False, True, True])
print("IS MORNING:", is_morning)
print("IS RAINING:", is_raining)
print("-" * 50)

### Logical Operators (&, |)

# Use '&' (AND) to find when it's both morning and raining
morning_and_raining = (is_morning & is_raining)

# Use '|' (OR) to find when it's either morning or raining
morning_or_raining = is_morning | is_raining

print("\nMORNING & (AND) RAINING:", morning_and_raining)
print("MORNING | (OR) RAINING:", morning_or_raining)

IS MORNING: tensor([ True, False, False,  True])
IS RAINING: tensor([False, False,  True,  True])
--------------------------------------------------

MORNING & (AND) RAINING: tensor([False, False, False,  True])
MORNING | (OR) RAINING: tensor([ True, False,  True,  True])


In [ ]:
# Sales data for 3 products over 4 months
sales_data = torch.tensor([[100, 120, 130, 110],   # Product A
                           [ 90,  95, 105, 125],   # Product B
                           [140, 115, 120, 150]    # Product C
                          ], dtype=torch.float32)

print("ORIGINAL SALES DATA:\n\n", sales_data)
print("-" * 45)

### START CODE HERE ###

# 1. Calculate total sales for Product B.
total_sales_product_b = None

# 2. Find months where sales for Product C were > 130.
high_sales_mask_product_c = None

# 3. Get sales for Feb and Mar for all products.
sales_feb_mar = None

### END CODE HERE ###

print("\nTotal Sales for Product B:                   ", total_sales_product_b)
print("\nMonths with >130 Sales for Product C (Mask): ", high_sales_mask_product_c)
print("\nSales for Feb & Mar:\n\n", sales_feb_mar)

In [ ]:
# A batch of 4 grayscale images, each 3x3
image_batch = torch.rand(4, 3, 3)

print("ORIGINAL BATCH SHAPE:", image_batch.shape)
print("-" * 45)

### START CODE HERE ###

# 1. Add a channel dimension at index 1.
image_batch_with_channel = None

# 2. Transpose the tensor to move the channel dimension to the end.
# Swap dimension 1 (channels) with dimension 3 (the last one).
image_batch_transposed = None

### END CODE HERE ###


print("\nSHAPE AFTER UNSQUEEZE:", image_batch_with_channel.shape)
print("SHAPE AFTER TRANSPOSE:", image_batch_transposed.shape)

In [ ]:
# Sensor readings (5 time steps)
temperature = torch.tensor([22.5, 23.1, 21.9, 22.8, 23.5])
humidity = torch.tensor([55.2, 56.4, 54.8, 57.1, 56.8])

print("TEMPERATURE DATA: ", temperature)
print("HUMIDITY DATA:    ", humidity)
print("-" * 45)

### START CODE HERE ###

# 1. Concatenate the two tensors.
# Note: You need to unsqueeze them first to stack them vertically.
combined_data = None

# 2. Create the weights tensor.
weights = None

# 3. Apply weights using broadcasting.
# You need to reshape weights to [2, 1] to broadcast across columns.
weighted_data = None

# 4. Calculate the weighted average for each time step.
weighted_average = None

### END CODE HERE ###

print("\nCOMBINED DATA (2x5):\n\n", combined_data)
print("\nWEIGHTED DATA:\n\n", weighted_data)
print("\nWEIGHTED AVERAGE:", weighted_average)

In [ ]:
# Data for 8 taxi trips: [distance, hour_of_day]
trip_data = torch.tensor([
    [5.3, 7],   # Not rush hour, not long
    [12.1, 9],  # Morning rush, long trip -> RUSH HOUR LONG
    [15.5, 13], # Not rush hour, long trip
    [6.7, 18],  # Evening rush, not long
    [2.4, 20],  # Not rush hour, not long
    [11.8, 17], # Evening rush, long trip -> RUSH HOUR LONG
    [9.0, 9],   # Morning rush, not long
    [14.2, 8]   # Morning rush, long trip -> RUSH HOUR LONG
], dtype=torch.float32)


print("ORIGINAL TRIP DATA (Distance, Hour):\n\n", trip_data)
print("-" * 55)


### START CODE HERE ###

# 1. Slice the main tensor to get 1D tensors for each feature.
distances = None
hours = None

# 2. Create boolean masks for each condition.
is_long_trip = None
is_morning_rush = None
is_evening_rush = None

# 3. Combine masks to identify rush hour long trips.
# A trip is a rush hour long trip if it's (a morning OR evening rush) AND a long trip.
is_rush_hour_long_trip_mask = None

# 4. Reshape the new feature into a column vector and cast to float.
new_feature_col = None

### END CODE HERE ###

print("\n'IS RUSH HOUR LONG TRIP' MASK: ", is_rush_hour_long_trip_mask)
print("\nNEW FEATURE COLUMN (Reshaped):\n\n", new_feature_col)

# You can now concatenate this new feature to the original data
enhanced_trip_data = torch.cat((trip_data, new_feature_col), dim=1)
print("\nENHANCED DATA (with new feature at the end):\n\n", enhanced_trip_data)